backend = "xrender";
# glx-no-stencil = true;
# glx-no-rebind-pixmap = true;
use-damage = true;
xrender-sync-fence = true;

vsync = false;
unredir-if-possible = true;
unredir-if-possible-delay = 0;

shadow = false;
fading = false;
blur-background = false;

detect-rounded-corners = false;
detect-client-opacity = true;
detect-transient = true;
detect-client-leader = true;
