#!/bin/sh

set -eu

SYSTEM_INSTALL_CMD='pacman -S'

# Set variables
SRC_DIR=$HOME/.local/share/src
LF_DIR=$HOME/.config/lf
VIM_DIR=$HOME
NVIM_DIR=$HOME/.config/nvim
NVIM_NEW_DIR=$HOME/.nvim
REPOS_LINK='https://github.com/iakobvs'

# Mkdir SRC_DIR
mkdir -p $HOME/.local
mkdir -p $HOME/.local/share
mkdir -p $HOME/.local/share/src

# Symlink configs
mkdir -p "$LF_DIR"
ln -s $HOME/.lfrc "$LF_DIR/lfrc"
ln -s $HOME/.lfrc-icons "$LF_DIR/icons"

# Add nvim cofiguration
echo "source $NVIM_NEW_DIR/init.vim" >> "$NVIM_DIR/init.vim"
# Add vim configuration
echo "source $NVIM_NEW_DIR/init.vim" >> "$VIM_DIR/.vimrc"

# Clone my repos
cd "$SRC_DIR"
git clone "$REPOS_LINK/dwm"
git clone "$REPOS_LINK/dwmblocks-fast"
git clone "$REPOS_LINK/st"
git clone "$REPOS_LINK/lf"

# Install programs
# dwm
cd dwm
make
sudo make install
cd ..

# dwmblocks-fast
cd dwmblocks-fast
make
sudo make install
cd ..

# st
cd st
make
sudo make install
cd ..

# lf
cd lf
$SYSTEM_INSTALL_CMD go
CGO_ENABLED=0 go install -ldflags="-s -w"
cd ..

# Autosuggestions
# pacman -S zsh-autosuggestions
