nn ;vd :edit $HOME/.local/src/dwm/config.h<CR>
nn ;vs :edit $HOME/.local/src/st/config.h<CR>
nn ;vdw :edit $HOME/.local/src/dwmblocks/blocks.h<CR>
nn ;vsl :edit $HOME/.local/src/slstatus/config.h<CR>
nn ;xi :edit $HOME/.xinitrc<CR>
nn ;vp :edit $HOME/.config/picom.conf<CR>
nn ;vvim :edit $HOME/.nvim/default.vim<CR>
nn ;zs :edit $HOME/.zsh/.zshrc<CR>
nn ;va :edit $HOME/.zsh/.zsh_aliases<CR>
nn ;vap :edit $HOME/.local/share/alias/aliases<CR>
nn ;vlf :edit $HOME/.lfrc<CR>
